feed_id: hst
source_type: djangoplicity
default_copyright: Public domain
default_license_id: CC-PDDC
default_constellations_handle: hubble
default_prepend_catfile: studieshubble
publish_url_prefix: http://data1.wwtassets.org/feeds/hst/
astropix_publisher_id: esahubble

djangoplicity:
  base_url: https://esahubble.org/images/
